---
- name: Atualizar sistemas Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Atualizar lista de pacotes
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Atualizar pacotes
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
